default: &default
    adapter: mysql2
    encoding: utf8mb4
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
    host: <%= ENV['DB_HOST'] %>
    port: <%= ENV['DB_RAILS_PORT_INT'] %>

development:
    <<: *default
    database: rspec_template_development # Change this to your database name

test:
    <<: *default
    database: rspec_template_test # Change this to your database name

production:
    <<: *default
    database: rspec_template_production # Change this to your database name